name: address
version: 0.1.0
description: >-
  Addresses internationalization library. Format various physical addresses
  in various languages and build localized address forms.
repository: https://github.com/leancodepl/address

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  lint: ^1.5.1
  test: ^1.16.4
